name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  install-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version
  tests:
    runs-on: ubuntu-latest
    needs: install-go
    steps:
      - name: Run builds
        run: run-builds.sh